pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'kruti28/flask-app'
        DOCKER_TAG = "${BUILD_NUMBER}"
        K8S_NAMESPACE = 'devops-demo'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/admin8856/devops-observability.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        docker.push("${DOCKER_TAG}")
                        docker.push("latest")
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh """
                    helm upgrade --install myapp ./helm-chart \
                        --set image.repository=${DOCKER_IMAGE} \
                        --set image.tag=${DOCKER_TAG} \
                        --namespace ${K8S_NAMESPACE} \
                        --create-namespace
                """
            }
        }
        stage('Verify Deployment') {
            steps {
                sh "kubectl get pods -n ${K8S_NAMESPACE}"
            }
        }
    }
    post {
        success { echo "Pipeline Success!" }
        failure { echo "Pipeline failed." }
    }
}
